# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Nqlite < Formula
  desc "Easy, lightweight, relational database using sqlite and nats jetstream"
  homepage "https://github.com/voxoco/nqlite"
  url "https://github.com/voxoco/nqlite/archive/v1.1.0.tar.gz"
  sha256 "761afd6f2eca028bf6768ef2df4dab424ce8bbb7ce107b6b7e9d0c1d13678538"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/voxoco/nqlite/releases/download/v1.1.0/nqlite-1.1.0-darwin-amd64.tar.gz"
      sha256 "9a879cacca4436a514914e9d22e857f69db8c358e97e3b096bee92eeb18cea9b"
    end

    on_arm do
      url "https://github.com/voxoco/nqlite/releases/download/v1.1.0/nqlite-1.1.0-darwin-arm64.tar.gz"
      sha256 "9480189b7bbb96219df46e0ac2590afd17f6c2806743fac8f570ee15700ee631"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/voxoco/nqlite/releases/download/v1.1.0/nqlite-1.1.0-linux-amd64.tar.gz"
      sha256 "b78e025eb448e2377f5f8ae6fea262db94861d62274ce75ffd277483e237044d"
    end
  end

  def install
    bin.install "nqlite"
  end
end
